### ISSUE TITLE
Question about "Freezing Object Properties"

### ISSUE THREAD

**Issue by ericcornelissen** [SoheilKhodayari/DOMClobbering#13]
The [Defenses and Mitigation Techniques](https://domclob.xyz/domc_wiki/defenses/#freezing-object-properties) page [currently](https://github.com/SoheilKhodayari/DOMClobbering/blob/fd534e8599280234d31ebeff89575f4a257608d7/domc_wiki/defenses/index.md) says:

> **Freezing Object Properties**
> Another way to mitigate DOM Clobbering is to freeze DOM object properties[[3]](https://link.springer.com/chapter/10.1007/978-3-319-24174-6_2), e.g., via [Object.freeze()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) method, which prevents the object to be overwritten by named DOM elements.
> 
> While effective, determining all objects and object properties that need to be frozen is a non-trivial, error-prone task. Also, sealed objects cannot be changed anymore, hindering the dynamic composition of webpages.

My first observation is that it actually seems relatively (compared to say prototype pollution) straightforward to determine what objects needs to be frozen, namely: `window`, `document`, and all `HTMLFormElement`s (based on https://github.com/whatwg/html/issues/2212#issuecomment-268957447). Would you agree?

However, more importantly, my second observation is that freezing is actually not possible in most cases! From my testing, the only situation in which freezing (or [sealing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal), or [preventExtensioning](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions)) is "supported" is when doing `Object.freeze(document)` in a Chromium based browser.

I have tested `window` and `HTMLFormElement`s in Chromium and Firefox as well as `document` in Firefox and found all of these results in an error being thrown because these objects are not freezable. Did you do any testing on this? If so, what were your findings?

Lastly, is there anything this item on the defenses page was meant to cover that I missed here? I would be curious to know about it 🙂

**Comment by SoheilKhodayari** [comment]
The defense webpage aims to provide a list of possible solutions that may have some effectiveness against DOM Clobbering. Ideally, these solutions can be used together as defense-in-depth. See also our OWASP [DOM Clobbering Prevention Cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/DOM_Clobbering_Prevention_Cheat_Sheet.html).


>  it actually seems relatively (compared to say prototype pollution) straightforward to determine what objects needs to be frozen. Would you agree?

> I have tested window and [...]  because these objects are not freezable

As you discovered, freezing the entire window / document is not possible nor even practical (e.g., due dynamic page updates). Freezing native window/document properties may also not be possible. 

The text is talking about custom variables and document properties defined in a program that could be clobberable, like x.y. I disagree, I don't think it is straightforward for developers to track and pinpoint all these variables for freezing : )

**Comment by ericcornelissen** [comment]
> The text is talking about custom variables and document properties defined in a program that could be clobberable, like x.y.

Could you elaborate on this point? I don't think I understand what you mean. My understanding is that:

The only way to use freezing to prevent, say, `x` from clobbering `document.x` is by freezing `document` (in Chromium at least). If you freeze `document.x` instead, you can still clobber `document.x` and the resulting read of `document.x.y` will read `y` on the clobbered `document.x` object, which means the freezing has no effect. Here's a demo of this behavior: <https://freezing-against-x-y-clobbering.glitch.me/> (tested on Chromium).

I haven't tested `<form>`s but my intuition is that they should work the same as `document`. `window` is not applicable in this context because once `window.x` is defined it cannot be clobbered anyway.

**Comment by SoheilKhodayari** [comment]
Sure, here's an example of object freezing preventing the clobbering of `document.x`. 

```<!DOCTYPE html>
<html>
<head></head>
<body>
<script type="text/javascript">
  var freezingEnabled = true;

  // clobberable property
  document.x = 1;

  if(freezingEnabled){
    // define and freeze `x` property on `document`
    Object.defineProperty(document, 'x', {
        value: document.x, //  the initial value
        writable: false, // prevent changes to the value
        configurable: false, // prevent redefinition or deletion
        enumerable: true // make it visible during enumeration
    });
  }

  // simulate an attacker 
  // injecting a markup with colliding named properties
  // to overshadow document.x
  var img = document.createElement('img');
  img.setAttribute("name", "x");
  img.setAttribute("src", "clobbered")
  document.body.appendChild(img);
  
  // read protected property
  console.log(document.x);

</script>

</body>
</html>
```

**Comment by SoheilKhodayari** [comment]
Upon reviewing the text in the wiki again, it seems the potential misunderstanding might arise from the emphasis on a specific API, particularly the `Object.freeze()` method, rather than the broader concept of freezing objects? I mean, there may be also other ways to achieve this : ) 

What do you think?

**Comment by ericcornelissen** [comment]
Thank you very much! That does work indeed (you can even set `writable: true`).


> Upon reviewing the text in the wiki again, it seems the potential misunderstanding might arise from the emphasis on a specific API, particularly the `Object.freeze()` method, rather than the broader concept of freezing objects?

That's definitely part of why I was confused. It also doesn't help that, still after your example, `Object.freeze()` has limited to no use (outside of `document` in Chromium, where it's unclear if it's intentional). 

> I mean, there may be also other ways to achieve this : )

Possibly, still I think it would be useful to call `Object.defineProperty` with `configurable: false` out explicitly.


> What do you think?

Unless you have an example of a use case for `Object.freeze` beyond `document` in Chromium, I personally think it would be best to rewrite the wiki with the `Object.defineProperty` example instead (and probably the OWASP cheatsheet too).

**Comment by SoheilKhodayari** [comment]
Thanks a lot, that makes sense to me! 

Let's update the wiki with `Object.defineProperty` then. Would you like to submit a PR? 🙂

**Comment by ericcornelissen** [comment]
Sounds good, I will try to submit a PR asap 👍

**Comment by ericcornelissen** [comment]
> I haven't tested `<form>`s but my intuition is that they should work the same as `document`.

For the record: using the `Object.defineProperty` strategy for properties of `<form>`s does not appear to prevent clobbering in Chromium but it does in Firefox...

See <https://configurable-false-against-clobbering.glitch.me/>
