### ISSUE TITLE
Confusion about the guideline "Do Not Use Document for Global Variables"

### ISSUE THREAD

**Issue by ericcornelissen** [SoheilKhodayari/DOMClobbering#9]
The [Patterns & Guidelines Wiki page](https://domclob.xyz/domc_wiki/indicators/patterns.html) [currently](https://github.com/SoheilKhodayari/DOMClobbering/tree/ed808a345911ecb9bbb81624c59d13b8d00b758e) states:

> **Do Not Use Document for Global Variables**
> Properties of `document` can always be overwritten by DOM Clobbering, even immediately after they are assigned a value, as in pattern C. Accordingly, developers should refrain from using `document` as a mean to store and retrieve global values. Instead, they can declare variables with `const` or `var` in the global context, or use the [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) object.

I'm not entirely sure I understand the intent of, or agree with, the last sentence.

- Suggesting to declare variables with `const` doesn't work, this is actually explained in the _Explicit Variable Declarations_ guideline.
- Suggesting to use `globalThis` (or `window` for that matter) is dangerous since it should be avoided because of (e.g.) pattern A - I know this is supposed to be about not using `document` for global variables (which is worse because it allows for shadowing too), but suggesting something that is still dangerous seems counterproductive.

**Comment by SoheilKhodayari** [comment]
> Suggesting to use globalThis (or window for that matter) is dangerous since it should be avoided because of (e.g.) pattern A - I know this is supposed to be about not using document for global variables (which is worse because it allows for shadowing too), but suggesting something that is still dangerous seems counterproductive.

I agree, this guideline is all about not using `document` to pass globals and could be improved. Would you be willing to submit a PR? 


> Suggesting to declare variables with const doesn't work

While using `const` or `var` for globals pollutes the global scope, it prevents clobbering of variables over document/window. For example:

```
const x = "constant";
```

This cannot be clobbered by injecting `id/name=x` and using `document/window.x`


Am I missing something?

**Comment by ericcornelissen** [comment]
> I agree, this guideline is all about not using `document` to pass globals and could be improved. Would you be willing to submit a PR?

I'd be happy to - and to clarify/reiterate, my main concern is that the text is recommended using something that is still dangerous in a similar way.


> While using const or var for globals pollutes the global scope, it prevents clobbering of variables over document/window. For example:
>
> ```
> const x = "constant";
> ```
>
> This cannot be clobbered by injecting `id/name=x` and using `document/window.x`
>
>Am I missing something?

I think you are missing something, see this demo: <https://var-let-const-clobbering.glitch.me/>. Only the `var` declared variable takes precedence over clobbering and it only does on `window`.

Like I mentioned, the [Explicit Variable Declarations](https://github.com/SoheilKhodayari/DOMClobbering/blob/ed808a345911ecb9bbb81624c59d13b8d00b758e/domc_wiki/indicators/patterns.md#explicit-variable-declarations) section explains:

> [...]. As an alternative solution, developers can initialize those variables with the default value when they are undefined using var declarations, which prevents named properties to overshadow them according to the [named property visibility algorithm](https://webidl.spec.whatwg.org/#legacy-platform-object-abstract-ops). [...]

**Comment by SoheilKhodayari** [comment]
I see, then it would be great to revise the text as you suggested above. 

On the top of that, would it also make sense to add a table to enumerate all the cases? 

| Declaration | Target      | Injection     | Clobbered |
|-------------|-------------|-------------------------|-----------|
| `x = 1`     | window.x    | `id=x` OR `name=x`     | No       |
| `x = 1`     | doc.x       | `id=x` OR `name=x`     | Yes       |
| `x = 1`     | x           | `id=x` OR `name=x`     | No       |
| `var x = 1` | window.x    | `id=x` OR `name=x`     | No       |
| `var x = 1` | doc.x       | `id=x` OR `name=x`     | Yes       |
| `var x = 1` | x           | `id=x` OR `name=x`     | No       |
| `const x = 1` | window.x  | `id=x` OR `name=x`     | Yes       |
| `const x = 1` | doc.x     | `id=x` OR `name=x`     | Yes       |
| `const x = 1` | x         | `id=x` OR `name=x`     | No       |
| `let x = 1` | window.x    | `id=x` OR `name=x`     | Yes       |
| `let x = 1` | doc.x       | `id=x` OR `name=x`     | Yes       |
| `let x = 1` | x           | `id=x` OR `name=x`     | No       |

**Comment by ericcornelissen** [comment]
> I see, then it would be great to revise the text as you suggested above.
>
> On the top of that, would it also make sense to add a table to enumerate all the cases?

👍 I'll send something in as soon as possible.
